runtime: python37

instance_class: F2

env_variables:
  BUCKET_NAME: "gs://greenertronics-42"

handlers:

- url: /images
  static_dir: static/images

- url: /.*
  secure: always
  redirect_http_response_code: 301